### PR TITLE
Add data encryption support according to the bthome protocol

### LINKED ISSUE #1: Encryption with BindKey?
It would be very useful to add a security layer by encrypting the packets with a BindKey (just like pvvx firmware can do it, sends BTHome broadcasts encrypted) - HA will automatically ask for the key when adding the device to it.

### PR DESCRIPTION
**Pull request by junchao98**
hello everyone,
 
This submission I tested normal in the following cases
 1. Encryption of individual sensor data
 2. Encrypting multiple sensor data
 3. No encryption

### CODE REVIEW

**Comment by stumpylog** [comment]
Awesome, thanks for the contribution.  I'll have to pull my sensor package out of its case to test this, so it may take a few more days before I can merge it.

Just glancing through, it makes sense.  I do see what looks like some formatting diffs.  Could you run the clang formatter (there's `format.sh` for it)?  Thanks!

**Comment by Chreece** [comment]
@junchao98 if you have time could you port your code to the general ESP32 example to finally have one with encryption?
https://github.com/Chreece/BTHomeV2-ESP32-example
(my programming skills are unfortunately basic)

**Comment by junchao98** [comment]
> @junchao98 if you have time could you port your code to the general ESP32 example to finally have one with encryption? https://github.com/Chreece/BTHomeV2-ESP32-example (my programming skills are unfortunately basic)

No problem, I will submit the code in the near future

**Comment by countrysideboy** [comment]
> > @junchao98 if you have time could you port your code to the general ESP32 example to finally have one with encryption? https://github.com/Chreece/BTHomeV2-ESP32-example (my programming skills are unfortunately basic)
> 
> No problem, I will submit the code in the near future

Great! Thanks.

**Comment by stumpylog** [comment]
Testing this change out, I get an abort here:
```
ESP_ERROR_CHECK failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x40090fb8
file: "./main/task_ble.cpp" line 112
func: void task_ble_entry(void*)
expression: esp_ble_gap_config_adv_data_raw(&advertData[0], dataLength)
```

Presumably, this is due to the advertisement being 35 bytes, more than the 31 allowed.  It should probably check that and warn at least before aborting.

Edit: In fact, it would probably be good to support encryption, but no name, as the encryption adds so many extra bytes

**Comment by stumpylog** [comment]
Once I changed up the naming to be short enough (exactly 31 bytes), Home Assistant did pick it up as encryption and the bind key worked.

Just a small tweak to try and make it a little more friendly of an error I think, and I can merge it in

**Comment by junchao98** [comment]
> Once I changed up the naming to be short enough (exactly 31 bytes), Home Assistant did pick it up as encryption and the bind key worked.
> 
> Just a small tweak to try and make it a little more friendly of an error I think, and I can merge it in

Yes, the esp-idf api has a requirement for maximum data length.

**Comment by stumpylog** [comment]
I know this looks closed, that's what I get for trying to manage too many remotes.  I tweaked the changes a little so it won't abort if too long, and merged in the commits.

**Comment by countrysideboy** [comment]
> > @junchao98 if you have time could you port your code to the general ESP32 example to finally have one with encryption? https://github.com/Chreece/BTHomeV2-ESP32-example (my programming skills are unfortunately basic)
> 
> No problem, I will submit the code in the near future

I have ported your code to the BTHomeV2-ESP32-example project, thanks for your hard working.

**Pull request closed without merging**
